### ISSUE TITLE
Angular-snap doesn't work together with ngSticky

### ISSUE THREAD

**Issue by anatoly314** [jtrussell/angular-snap.js#113]
Duplicate my question from SO here http://stackoverflow.com/questions/37527823/angular-snap-doesnt-work-together-with-ngsticky

----------------------------------------------------

trying to use together [Angular-Snap][1] with [ngSticky][2] but it doesn't work, panel which should stay *sticky* is being scrolled. 

I've prepared two examples:

 - Example with Angular-Snap which **doesn't work**: https://plnkr.co/edit/ARhUti3jJCEjB8sLL5q0?p=preview
 - Example without Angular-Snap which **works**: 
https://plnkr.co/edit/QJSQelcdUP2AamFBuNiH?p=preview

You can expand in both examples accordion panel and try to scroll to see the difference. 

If I remove in **1st**, *non-working example* `angular-snap.css` file it begins to work, but obviously I need it. I couldn't debug this issue further, so any help would be appreciated.

  [1]: https://github.com/jtrussell/angular-snap.js
  [2]: https://github.com/d-oliveros/ngSticky

**Comment by jtrussell** [comment]
Just curious - have you tried using:

- `angular-snap-only.css` - from this repo
- `snap.css` - from the Snap.js repo

Rather than the combined `angular-snap.css`? IIRC the combined css file also includes some extra things (e.g. smooth scrolling) that may be getting in the way here. In general I'd recommend using the dedicated CSS files for each library independently. We're just providing a bundled version here for convenience and backward compatibility.

If that still doesn't work it'll at least tell us if the issue lies in the Snap.js css or ours.

**Comment by anatoly314** [comment]
Yes, it has solved this issue. Thank you very much!

**Comment by anatoly314** [comment]
Only now seen that `angular-snap-only.css` and `snap.css` not enough, right menu now shown (left menu I haven't checked), you need to add manually:
````
.snap-drawer-left {
  left: 0;
}
.snap-drawer-right {
  right: 0;
}
````

**Comment by jtrussell** [comment]
It looks like there rules are in place: https://github.com/jakiestfu/Snap.js/blob/develop/snap.css#L55-L63
