### ISSUE TITLE
Events with multiple drawers?

### ISSUE THREAD

**Issue by timmyomahony** [jtrussell/angular-snap.js#84]
I am trying to tie events to the opening/closing of multiple drawers (one on each side of my content) but I can't seem to get it to work. My app is set up as follows:

    <div snap-drawers></div>
        <div ng-controller="left-ctrl" snap-drawer="left"></div>
        <div ng-controller="right-ctrl" snap-drawer="right"></div>
    </div>
    <div ng-controller="content-ctrl" snap-content>...</div>

In controller one:

    app.controller('LeftCtrl', ['$scope', 'snapRemote', 
        function($scope, snapRemote){
            snapRemote.getSnapper("right").then(function(snapper) {
                snapper.on('open', function() {
                    console.log("Open Left");
                });
                snapper.on('close', function() {
                    console.log("Close Left");
                });
            });
    }]);
  

In controller two:
    
    app.controller('RightCtrl', ['$scope', 'snapRemote', 
        function($scope, snapRemote){
            snapRemote.getSnapper("right").then(function(snapper) {
                snapper.on('open', function() {
                    console.log("Open Right");
                });
                snapper.on('close', function() {
                    console.log("Close Right");
                });
            });
    }]);

Is it actually possible to listen for the opening/closing of each drawer individually? I know that `getSnapper` takes a `snapId` which corresponds to the entire drawer+content so the above won't work.

**Comment by jtrussell** [comment]
As you say the `snapId` actually corresponds to just the content element. The "drawers" are essentially styled divs that happen to be along for the ride. So the event model we have to work with doesn't really note which drawer happens to be showing, just which content element is opening/closing.

It would be possible to rig something up with multiple `snap-content` elements, one dedicated to each side, but I think I'd recommend making my own "right"/"left" events and fire those by inspecting the state of the snapper object.

Here's a pretty rough example, you'd attach this directive to your `snap-content` element:

```javascript
app.directive('snapSideEventEmitter', function($rootScope, snapRemote) {
  return {
    link: function() {
      snapRemote.getSnapper().then(function(snapper) {
        snapper.on('animated', function() {
          var eventName = {
            closed: 'SNAP_CLOSED_EVENT',
            left: 'SNAP_LEFT_EVENT',
            right: 'SNAP_RIGHT_EVENT'
          }[snapper.state().state];
          $rootScope.$broadcast(eventName, snapper);
        });
      });
    }
  };
});
```

And just for completeness here's a working demo: http://jsbin.com/disoru/2/edit?js,console,output

You'll notice that I use the `'animated'` event rather than `'open'`. I didn't seen a great way to get the info I wanted from the snapper state until after it has finished its animations but maybe you'll have more luck.

**Comment by timmyomahony** [comment]
Thanks for getting back to me with such a detailed reply. I'll try that out and see how I get on.

**Comment by jtrussell** [comment]
Sure thing, hope that helps!
