### ISSUE TITLE
Closing while still dragging wont close completly

### ISSUE THREAD

**Issue by mikila85** [jtrussell/angular-snap.js#89]
left \ right must be disabled for this, cant have both menus available.
When dragging menu you can "play" with it open\close  left\right.

if try open and without leaving mouse close fast it (Without leaving the finger\mouse) it wont close completely and stuck half way even if mouse reaches the close point.

![image](https://cloud.githubusercontent.com/assets/3965957/7252932/9b7183d2-e841-11e4-8c21-bff05d378ea3.png)

**Comment by jtrussell** [comment]
Would you mind trying to reproduce your issue here: http://jsbin.com/toxeke/1

**Comment by mikila85** [comment]
you are right bro, need to have left disabled or right disabled to reproduce it.

**Comment by jtrussell** [comment]
Ok, mind trying this one? http://jsbin.com/toxeke/2

**Comment by mikila85** [comment]
surely reproduced. tried it same problem..
try Holding mouse going right (to open) and not leaving it try close.. it wont reach close stuck in middle like my picture above.

**Comment by mikila85** [comment]
must move mouse fast. if do it slow there are only few pixels stuck it is almost unnoticable.

**Comment by jtrussell** [comment]
OK. I wasn't able to reproduce the issue myself but the example above just uses [Snap.js](https://github.com/jakiestfu/Snap.js) without the angular-snap wrapper. It seems like your issue lies with Snap.js itself. I did a quick scan through their open issues and didn't see anything resembling what you're describing so you might want to create an issue there. This repo is really a thin wrapper around Snap.js to make it play nice with Angular.

**Comment by mikila85** [comment]
thx.
